// Lyrics for "Still Loving You" by Scorpions with timestamps
export const lyrics = [
    { time: 0, text: "" },
    { time: 15, text: "Time, it needs time" },
    { time: 19, text: "To win back your love again" },
    { time: 25, text: "I will be there, I will be there" },
    { time: 32, text: "Love, only love" },
    { time: 37, text: "Just shouldn't be thrown away" },
    { time: 43, text: "I will be there, I will be there" },
    { time: 51, text: "If we'd go again" },
    { time: 55, text: "All the way from the start" },
    { time: 60, text: "I would try to change" },
    { time: 64, text: "The things that killed our love" },
    { time: 70, text: "Your pride has built a wall, so strong" },
    { time: 78, text: "That I can't get through" },
    { time: 85, text: "Is there really no chance" },
    { time: 90, text: "To start once again" },
    { time: 95, text: "I'm loving you" },
    { time: 105, text: "Try, baby try" },
    { time: 110, text: "To trust in my love again" },
    { time: 116, text: "I will be there, I will be there" },
    { time: 123, text: "Love, our love" },
    { time: 128, text: "Just shouldn't be thrown away" },
    { time: 134, text: "I will be there, I will be there" },
    { time: 142, text: "If we'd go again" },
    { time: 146, text: "All the way from the start" },
    { time: 151, text: "I would try to change" },
    { time: 155, text: "The things that killed our love" },
    { time: 161, text: "Your pride has built a wall, so strong" },
    { time: 169, text: "That I can't get through" },
    { time: 176, text: "Is there really no chance" },
    { time: 181, text: "To start once again" },
    { time: 220, text: "If we'd go again" },
    { time: 224, text: "All the way from the start" },
    { time: 229, text: "I would try to change" },
    { time: 233, text: "The things that killed our love" },
    { time: 239, text: "Yes, I've hurt your pride, and I know" },
    { time: 247, text: "What you've been through" },
    { time: 254, text: "You should give me a chance" },
    { time: 259, text: "This can't be the end" },
    { time: 265, text: "I'm still loving you" },
    { time: 274, text: "I'm still loving you" },
    { time: 283, text: "I need your love" },
    { time: 292, text: "I'm still loving you" },
    { time: 310, text: "" }
];

export default lyrics;
